### ISSUE TITLE
Datastore Questions

### ISSUE THREAD

**Issue by nickbe** [psono/psono-client#1]
I admint I'm a little bit confused by the databstores.

Is the 'default' datastore global or does it exist PER user?

And if i create a new datastore beside the "default" one, is this MY datastore and no other users have access to it?

**Comment by chickahoona** [comment]
Hi nickbe,
Every user has his own datastore.

If you create a ne datastore, then you have two datastores that only belong to you.

If you want to share content, then you can do that with a folder or directly with an entry by creating a share object around it.

Maybe this diagram helps you a bit:
https://doc.psono.com/mydoc_development_entity_model.html

Best regards
Sascha

**Comment by nickbe** [comment]
Thanks. This explains an older question regarding admin access rights - because every user is an admin on it's own for his own datastores.
