### ISSUE TITLE
URL check

### ISSUE THREAD

**Issue by misterunknown** [psono/psono-client#10]
Hi,

the web client checks the URL field when I try to add a new entry. This check seems to not cover all valid URLs, for example `http://localhost:3000` is not possible. However, when _changing_ the URL of an entry there seems to be no check at all, so that is my workaround for now.

Would it be sensible to remove the check everywhere? AFAIK the application does not care about the validity of the URL.

Cheers,
Marco

**Comment by chickahoona** [comment]
Hi misterunknown.

Thank you very much for your report. Ill for sure will investigate (the part where urls are not accepted even so they are properly formatted). 

About your second question. The check is required for additional features, e.g. links that open a website or the domain extraction to support autofill and so on. We have here another similar issue by another customer that I think would solve your issue too https://gitlab.com/psono/psono-client/issues/151

As the central place for issues is https://gitlab.com/psono/psono-client/issues I am closing this one here. I hope you understand but having to communicate across multiple threads and instances is extremely error prone.
