### ISSUE TITLE
Several issues with build 42c13453

### ISSUE THREAD

**Issue by vins31** [psono/psono-client#3]
Hi,
My team tested Psono on psono.pw for the first time with the build 42c13453.
While using Psono as a single user, it worked flawlessly, the interface is efficient, modern and very beautiful, however, while playing with group sharing (with 3 users), multiple issues occurred:
- the button "Accept new shares" in the Groups page duplicate folders from the datastore if you click on it a 2nd time.
- sometimes deleting a folder from the datastore (for the user who created it) may fail (you should find error 500 on psono.pw)
- sometimes, sharing a folder with a group from the datastore may not save the action (opening the Share pop-up reveals the checkboxs corresponding to the previously checked groups are unchecked)

**Comment by psono** [comment]
As we have not received any update we are closing this issue.
